name: CI - Test and Build (Latest)

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    if: github.repository == 'jt196/vanilla-cookbook'
    uses: ./.github/workflows/run-tests.yml

  docker-build-latest:
    if: github.repository == 'jt196/vanilla-cookbook'
    needs: run-tests
    uses: ./.github/workflows/docker-build.yml
    with:
      docker_tags: latest
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
